#!/usr/bin/env bash

if [ -z "$PROXY_PORT" ]; then
  echo "You must set the PROXY_PORT config var to create a TCP tunnel!"
  exit 1
fi

tunnelHost="ec2-52-26-62-97.us-west-2.compute.amazonaws.com"
tunnelPort=$((RANDOM%64535+1000))

eval "$(ssh-agent -s)"
eval "ssh-add-pass .ssh/proxy_rsa $SSH_PROXY_PASSPHRASE"

# Start the TCP tunnel
echo "Starting TCP tunnel on port ${PROXY_PORT}..."
eval "ssh -R *:${tunnelPort}:localhost:${PROXY_PORT} -N heroku@${tunnelHost} &"

if [ $? -ne 0 ]; then
  echo "Could not connect to proxy server. Your key may be expired. Please try redeploying."
  exit 1
fi

echo "Tunnel running at ${tunnelHost}:${tunnelPort}"

eval "$@"
